### ISSUE TITLE
input and output tapes share the same symbol table causing occasional surprise

### ISSUE THREAD

**Issue by dhdaines** [mhulden/pyfoma#35]
This is a somewhat marginal problem which can pop up when composing (somewhat artificial) FSTs:
```python
f1 = FST.re("(foo):(bar)")
print(list(f1.apply("foo")))
# prints ["bar"]
f2 =  FST.re("'':'foo' b a r:z")
print(list(f1.compose(f2).apply("foo")))
# prints [] ... you might expect it to print "foobaz"?
```
I'm not sure this is a serious problem as I'm having a hard time coming up with a less contrived example.  Feel free to close this if you can't think of one either :)

**Comment by mhulden** [comment]
This issue is well known and goes back at least 30 years among developers of FSM toolkits (e.g. the Xerox toolkit, and later, foma). The question is: how should one tokenize an input string when "applying" if the alphabet contains symbols that share a common prefix? In this example, "foo" and "f" are both in the alphabet and so the input string `foo` could be tokenized `['f','o','o']` or `['foo']`.  The output depends on which tokenization is chosen.

There are generally two obvious ways to handle this:

(1) tokenize with all possible factorizations, given the alphabet, then yield all outputs
(2) make some executive decision about how to resolve such ambiguities (tokenize greedily using shortest match, longest match, etc.)

All toolkits that I am aware of have chosen option (2), including PyFoma. Doing all factorizations slows down the input-string tokenization process significantly. Also, any FST that has overlapping prefixes in the alphabet is probably the result of a design error somewhere.

It's generally advisable to never introduce such ambiguities in the alphabet because the potential for confusion is so high. This is why multicharacter grammatical tags, such as `'[N]'`, `'+N'`, `'[ADJ]'`, `'+ADJ'` should always have some unique initial symbol (`'['` or `'+'`) that doesn't occur as  single symbol in the alphabet so we don't get an ambiguous factorization in the "apply" process.

Expert users who might actually want to work with ambiguous alphabets would probably want to exert fine-grained control over the tokenization of any input string and perform a manual composition instead of calling apply(), either as:

```python3
FST.re("foo") @ f1 @ f2
```

or 

```python3
FST.re("'foo'") @ f1 @ f2
```

and then extract the strings in the output projection of the resulting FST to get the desired result.

One potential addition to PyFoma could of course be to allow the user to provide a tokenizer function which could be passed as an optional argument to `apply()`, `generate()`, and `analyze()`. Currently the default `tokenize_against_alphabet()` processes the input string. I think that would be fine since the extra keyword argument would be transparent and doesn't force a layer of complexity onto the user, but I also think this is such a corner case that the optional tokenizer option may very well never be used by anyone...

**Comment by dhdaines** [comment]
Thank you for the really detailed response!  I agree, in any real use case, you'll have other problems before this one when using ambiguous multi-character symbols, and also as you say, it is possible to simply add the necessary arcs to represent the ambiguity and do composition manually.

Indeed, the added complexity of having a separate input alphabet (in tools that do use one) is usually unnecessary.  I'll close this but having the explanation is really useful, thanks again!
